### ISSUE TITLE
Consider using git submodules instead of copying over Yoga source code

### ISSUE THREAD

**Issue by victorporof** [bschwind/yoga-rs#13]
https://github.com/blog/2104-working-with-submodules

**Comment by bschwind** [comment]
I've mainly avoided this so far because the whole yoga repo is quite huge compared to just the C files they have.

**Comment by victorporof** [comment]
Git submodules won't check in the entire submodule repo, so there's no pollution involved (it's literally just a .gitmodules file). Local clones, however, do indeed pull the entire submodule.

The advantage of git modules is that it's easier to stay up to date with the dependencies.

**Comment by bschwind** [comment]
Right, the local clone is what I don't want to deal with, especially since it'll happen when someone has this as a dependency and does a `cargo build` the first time.

If maintenance becomes an issue then I might switch over to submodules but for now I'd rather not.

**Comment by victorporof** [comment]
Closing this. Not really that necessary.
