### ISSUE TITLE
Several types are missing, non-utilised or not exposed

### ISSUE THREAD

**Issue by victorporof** [bschwind/yoga-rs#15]
Accidental omission?

**Comment by bschwind** [comment]
Sorry, quite a few properties are missing in master at the moment. In the "tests" branch I'm going through and porting all tests, filling in missing properties and functionality when I come across them. I wouldn't recommend using this library until those tests are finished but if you need the missing properties this instant, that's the branch to look at.

**Comment by victorporof** [comment]
On this note I've found a few others. Noting them here as reference.

- [ ] FlexStyle::PaddingBottom doesn't exist.
- [ ] Dimension, Display, LogLevel, MeasureMode don't seem to be used anywhere.
- [ ] Overflow isn't exposed as a FlexStyle when it probably should.

**Comment by bschwind** [comment]
Here's a view of what's in the `tests` branch so far:

https://github.com/bschwind/yoga-rs/pull/10/files#diff-b4aea3e418ccdb71239b96952d9cddb6R30
