### ISSUE TITLE
Update yoga to a recent version

### ISSUE THREAD

**Issue by sercand** [bschwind/yoga-rs#36]
Facebook recently updated yoga license and switched to c++ from c. Also added some new features like `justify-content: space-evenly`

**Comment by bschwind** [comment]
Switching to C++ is a shame, it might be more difficult to correctly bind to their code now. I'll have to do some more research to see if it's viable.

**Comment by mehcode** [comment]
Doesn't look like it's actually C++. Just C in C++ source with some minor utility functions added if you're on a C++ compiler.

**Comment by mehcode** [comment]
Check out https://github.com/Nemikolh/yoga-sys
Perhaps this repo can leave the binding generation to that library and focus on the safe API?

**Comment by bschwind** [comment]
Implemented by #44
