### ISSUE TITLE
Suggest taffy instead of stretch

### ISSUE THREAD

**Issue by alice-i-cecile** [bschwind/yoga-rs#53]
Hi! I'm one of the authors of [taffy](https://github.com/dioxuslabs/taffy), a revived fork of the abandoned `stretch` crate linked in your README. We've fixed a number of serious bugs in the library, and continue to develop it actively.

It's probably more helpful to point users looking for a pure Rust flexbox implementation to us.

**Comment by bschwind** [comment]
Done!

https://github.com/bschwind/yoga-rs/blob/98eb320a5ac8e8e86735946891e0a07c85149f71/README.md

Thanks for letting me know, cool to see a revival of `stretch` :)

**Comment by alice-i-cecile** [comment]
Awesome! Yeah, we were relying on it over in `bevy_ui` and the team got fed up with unfixed bugs, performance issues and terrible docs.
